 platform :ios, '9.0'

target 'rahulIosTask' do
  use_frameworks!
   pod 'SVProgressHUD'
   pod 'ReachabilitySwift'
   pod 'Alamofire'

  target 'rahulIosTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rahulIosTaskUITests' do
    # Pods for testing
  end

end
